"""
Teste
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("teste meu teste")

default_args={
    "owner": "Renata Rocha Torres,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-02", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Renata Rocha Torres": "mailto:renata.rochat@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6o7avwj121j01iv1kpoc16r/cloud-ide/cm6o7m3zb11wy01l035hki1x6/cm6o7s94x11xp01l0uzv2grdb",
    },
)
def Teste():
    python_1 = python_1_func()

dag_obj = Teste()
